name: Prefect Build From .deploy

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
  PROD_WORKSPACE: ${{ secrets.PROD_WORKSPACE }}
  DEV_WORKSPACE: ${{ secrets.DEV_WORKSPACE }}

on:
  push:
    branches: [ feature-*  ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    # Checks out the code repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v3


    - name: Set up Python Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

####### PROD #######
    - name: Switch to prod workspace
      run: |
        prefect cloud workspace set -w ${{ env.PROD_WORKSPACE }}
        echo "WORK_POOL=prod" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/main'

    - name: Find and Run Changed Python Files
      run: |
        # Check for modified Python files
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')
        echo "Changed Python files: $files"
        
        for file in $files; do
          if grep -q '.deploy()' "$file"; then
            echo "Running $file"
            python $file
          fi
        done
      if: github.ref == 'refs/heads/main'

####### DEV #######
    - name: switch to dev
      run: |
        prefect cloud workspace set -w ${{ env.DEV_WORKSPACE }}
        echo "WORK_POOL=dev" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/heads/feature-')
  
    - name: Find and Run Changed Python Files
      run: |
        # Check for modified Python files
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')
        echo "Changed Python files: $files"
        
        for file in $files; do
            echo "Running $file"
            python $file
          fi
        done
      if: github.ref == 'refs/heads/feature-'

    env:
      BRANCH_REF: ${{ github.ref }}