name: Prefect Build From .deploy

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
  PROD_WORKSPACE: ${{ secrets.PROD_WORKSPACE }}
  DEV_WORKSPACE: ${{ secrets.DEV_WORKSPACE }}

on:
  push:
    branches: [ feature-*  ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    # Checks out the code repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v3


    - name: Set up Python Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

####### DEV #######
    - name: switch to dev
      run: |
        prefect cloud workspace set -w ${{ env.DEV_WORKSPACE }}
        echo "WORK_POOL=dev" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/heads/feature-')

    - name: Get changed python files
      id: changed-python-files
      uses: tj-actions/changed-files@v40
      with:
        files: '**/*.py'

    - name: Find and Run Changed Python Files
      run: |
        for file in ${{ steps.changed-python-files.outputs.all_changed_files }}; do
            echo "Running $file"
            python $file
        done
      if: startsWith(github.ref, 'refs/heads/feature-')

    env:
      BRANCH_REF: ${{ github.ref }}